<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.52" />
    <PackageReference Include="ScottPlot.WPF" Version="5.0.46" />
  </ItemGroup>

</Project>
